#!/bin/bash
   #################################################################
   #                                                               #
   #                 binary-os-gaming-setup                        #
   #           Copyright (C) 2022 Kainat quaderee                  #
   #       Licensed under the  non redistributable license      #
   #                                                               #
   #                                                               #
   #                                                               #
   #################################################################
 apt-get update -y
 apt-get upgrade -y
 apt-get remove lutris -y
 apt-get remove steam -y
 apt-get remove minigalaxy -y
flatpak uninstall  com.heroicgameslauncher.hgl -y
 apt-get remove obs-studio -y
flatpak uninstall net.davidotek.pupgui2 -y
 apt-get remove stella -y
 apt-get remove yabause -y
 apt-get remove dosbox -y
 add-apt-repository -r -y ppa:flexiondotorg/mangohud
 apt-get remove -y mangohud
 apt-get remove -y piper
 add-apt-repository -r -y ppa:openrazer/stable
 apt-get update -y
 apt-get remove openrazer-meta -y
 add-apt-repository -r -y ppa:polychromatic/stable
 apt-get update -y
 apt-get remove -y polychromatic
 apt-get remove -y vkbasalt
flatpak uninstall com.discordapp.Discord -y
 apt-get autoremove -y
 yad --info --width=500 --height=200  \
--text "GAMING-setup-done"
